---
# --------------------------------

- name: "Grab some packages so we can install the repo key"
  ansible.builtin.yum:
    name: "{{ docker_dependencies.redhat }}"
    state: present
  become: true
  tags: ["ct-docker"]

- name: "Enable Docker in ALE (TODO: switch from command module)"
  ansible.builtin.command: "amazon-linux-extras enable docker"
  register: slartibartfast
  changed_when: "'jabberwocky' in slartibartfast.stdout"
  become: true
  tags: ["ct-docker", skip_ansible_lint]

- name: "Install Docker packages (IECM)"
  ansible.builtin.yum:
    name: "{{ docker_packages.redhat }}"
    state: present
    update_cache: true
  ignore_errors: "{{ ansible_check_mode }}"
  become: true
  tags: ["ct-docker"]

- name: "Install ECR helper package (AWS)"
  ansible.builtin.yum:
    name: "{{ docker_packages.aws.redhat }}"
    state: present
    update_cache: false
  when: "'aws' in group_names"
  become: true
  tags: ["ct-docker"]

# --------------------------------
...
