---
# --------------------------------

- name: "Grab some packages so we can install the repo key"
  ansible.builtin.apt:
    name: "{{ docker_dependencies.debian }}"
    state: present
  become: true
  tags: ["ct-docker"]

- name: "Add Docker keyring"
  ansible.builtin.get_url:
    dest: "{{ docker_keyring_path }}"
    mode: "0644"
    url: "{{ docker_keyring_url }}"
  become: true
  tags: ["ct-docker"]

- name: "Add Docker repository"
  ansible.builtin.apt_repository:
    filename: docker
    repo: "deb [arch=amd64 signed-by={{ docker_keyring_path }}] {{ docker_repo_url }} {{ ansible_distribution_release }} stable"
    state: present
    update_cache: true
  register: reg_docker_repo
  become: true
  tags: ["ct-docker"]

- name: "Update package cache and install Docker packages (IECM)"
  ansible.builtin.apt:
    name: "{{ docker_packages.debian }}"
    state: present
    update_cache: "{{ reg_docker_repo is changed }}"
  ignore_errors: "{{ ansible_check_mode }}"
  become: true
  tags: ["ct-docker"]

- name: "Install ECR helper package (AWS)"
  ansible.builtin.apt:
    name: "{{ docker_packages.aws.debian }}"
    state: present
    update_cache: "{{ reg_docker_repo is changed }}"
  when: "'aws' in group_names"
  become: true
  tags: ["ct-docker"]

# --------------------------------
...
