---
# --------------------------------

- name: 'Added some directories under /usr/local'
  ansible.builtin.file:
    path: '{{ item }}'
    state: directory
    owner: root
    group: root
    mode: 0755
  loop: ['/usr/local/bin', '/usr/local/etc', '/usr/local/etc/bash.d']
  become: true
  tags:
  - ct-docker
  - ct-docker-scripts

- name: 'Copy bash include file over'
  ansible.builtin.copy:
    src: docker.sh
    dest: /usr/local/etc/bash.d
    owner: root
    group: root
    mode: 0644
  become: true
  tags:
  - ct-docker
  - ct-docker-scripts

- name: 'Copy convenience scripts over'
  ansible.builtin.copy:
    src: '{{ item }}'
    dest: /usr/local/bin
    owner: root
    group: root
    mode: '0755'
  loop:
  - dbuild.sh
  - drac.sh
  - drdi.sh
  - drun.sh
  become: true
  tags:
  - ct-docker
  - ct-docker-scripts

- name: 'Grab some packages so we can install the repo key'
  ansible.builtin.apt:
    name: '{{ docker_dependencies }}'
    state: present
  become: true
  tags:
  - ct-docker
  - ct-docker-pkg

- name: 'Add docker repo key'
  ansible.builtin.apt_key:
    url: 'https://download.docker.com/linux/ubuntu/gpg'
    validate_certs: true
    state: present
  become: true
  tags:
  - ct-docker
  - ct-docker-repo

- name: 'Add docker repository to APT'
  ansible.builtin.apt_repository:
    repo: 'deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ct_codename }} stable'
    state: present
    update_cache: true
    filename: docker
  register: reg_docker_repo
  become: true
  tags:
  - ct-docker
  - ct-docker-repo

- name: 'Update apt cache and install docker packages'
  ansible.builtin.apt:
    name: '{{ docker_packages }}'
    update_cache: '{{ reg_docker_repo is changed }}'
    state: present
  become: true
  tags:
  - ct-docker
  - ct-docker-pkg

- name: 'Add users to docker role'
  ansible.builtin.user:
    name: '{{ item }}'
    append: true
    groups: 'docker'
  loop: '{{ docker_users }}'
  become: true
  tags:
  - ct-docker
  - ct-docker-user

- name: 'Render logrotate config'
  ansible.builtin.template:
    src: logrotate.j2
    dest: /etc/logrotate.d/{{ item.filename }}
    owner: root
    group: root
    mode: '0644'
  vars:
    lr_count: '{{ item.count }}'
    lr_path: '{{ item.path }}'
    lr_size: '{{ item.size }}'
  loop: '{{ docker_logrotation }}'
  become: true
  tags:
  - ct-docker
  - ct-docker-hkp

- name: 'Start and enable docker service'
  ansible.builtin.service:
    name: docker
    enabled: true
    state: started
  become: true
  tags:
  - ct-docker
  - ct-docker-svc

# --------------------------------
# optional Docker Swarm set up

- name: 'Get local IP (assumes AWS host)'
  ansible.builtin.command: curl http://169.254.169.254/latest/meta-data/local-ipv4
  when:
  - docker_swarm_mode == 'master'
  - (ct_cloud|default('foo')) == 'aws'
  register: reg_ip
  check_mode: false
  become: true
  tags:
  - ct-docker
  - ct-docker-swarm

- name: 'Generate docker swarm key'
  ansible.builtin.shell: docker swarm init  --advertise-addr {{ reg_ip.stdout_lines[0] }} | grep 'docker swarm join ' > {{ docker_swarm_tmpfile }}
  args:
    creates: '{{ docker_swarm_tmpfile }}'
  when: docker_swarm_mode == 'master'
  become: true
  tags:
  - ct-docker
  - ct-docker-swarm

- name: 'Fetch swarm file'
  ansible.builtin.fetch:
    src: '{{ docker_swarm_tmpfile }}'
    dest: /tmp/
    flat: true
  when: docker_swarm_mode == 'master'
  become: true
  tags:
  - ct-docker
  - ct-docker-swarm

- name: 'Load docker swarm command'
  ansible.builtin.command: cat {{ docker_swarm_tmpfile }}
  when: docker_swarm_mode == 'minion'
  register: reg_join_command
  changed_when: false
  delegate_to: localhost
  tags:
  - ct-docker
  - ct-docker-swarm

- name: 'Tell minion to join swarm'
  ansible.builtin.shell: '{{ reg_join_command.stdout_lines[0] }}'
  when: docker_swarm_mode == 'minion'
  register: reg_join
  failed_when: (reg_join.rc|int > 0) and ('This node is already part of a swarm' not in reg_join.stderr)
  become: true
  ignore_errors: '{{ ansible_check_mode }}'
  # changed_when: TODO
  tags:
  - ct-docker
  - ct-docker-swarm

# --------------------------------
...
